package exception_handling;

public class sab {

	
	public static void main(String[] args) {
		
		 try{
			 int y= 10;
         	int p=0;
         	int u=y/p;
         	System.out.print(u);
         	
		            try{
		            	
		            	int array[]=new int[10];
		            }catch(ArrayIndexOutOfBoundsException e){
		            	System.out.println("Arithmetic Exception 1");
		            	
		            }     }

		    catch(ArithmeticException e){
		    	System.out.print("Arithmetic Exception 2");
		     
		    }
		 
		    
		  }
		}
	
	
		 
		 

	
		
	